# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthAssist' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthAssist
  pod 'TABSwiftLayout'
  pod 'Alamofire', '~> 4.7'
  pod 'JSONUtilities'
  pod 'AlamofireImage'
  pod 'TriLabelView'
end
